drop table if exists users, films, mpa_ratings, friends, genres, film_genres, film_likes cascade;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(300) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  description VARCHAR(500) NOT NULL,
  requestor_id BIGINT NOT NULL REFERENCES users (id) on delete cascade,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  description VARCHAR(500) NOT NULL,
  is_available BOOLEAN NOT NULL,
  request_id BIGINT REFERENCES requests (id) on delete cascade,
  owner_id BIGINT REFERENCES users (id) on delete cascade
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id BIGINT NOT NULL REFERENCES items (id) on delete cascade,
  booker_id BIGINT REFERENCES users (id) on delete cascade,
  status VARCHAR(8) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  feedback VARCHAR(1000) NOT NULL,
  item_id BIGINT NOT NULL REFERENCES items (id) on delete cascade,
  author_id BIGINT NOT NULL REFERENCES users (id) on delete cascade,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);